const tracks = [
    {
        albumCover: '../Assets/Images/Lydia_Run_Wild.jpeg',
        trackTitle: 'Georgia',
        trackAuthor: 'Lydia',
        trackAudio: '../Assets/Audio/Lydia-Georgia-10s.mp3',
        category: 'Indie',
        description: 'Georgia - 11th Track of the Run Wild Album, Produced by Lydia. Launched in 2015',
        imgText: 'Lydia Album Cover',
        youtubeLink: 'https://www.youtube.com/watch?v=GaH8conkRK8&ab_channel=Lydiabandchannel',
    },
    {
        albumCover: '../Assets/Images/poor_gqtis.jpg',
        trackTitle: 'POOR',
        trackAuthor: 'gqtis',
        trackAudio: '../Assets/Audio/gqtis-poor-10s.mp3',
        category: 'Phonk',
        description: 'Poor - 1st track of POOR Album by gqtis. Launched in 2022',
        imgText: 'POOR Album Cover',
        youtubeLink: 'https://www.youtube.com/watch?v=tV-fEIVBmEw&ab_channel=PHONKDOMAIN',
    },
    {
        albumCover: '../Assets/Images/In_Return_Odesza.jpg',
        trackTitle: 'Say My Name',
        trackAuthor: 'Odesza ft Zyra',
        trackAudio: '../Assets/Audio/Odesza-SayMyName-10s.mp3',
        category: 'Electronic',
        description: 'Say My Name from the In Return Album by Odesza Feat Zyra. Launched in 2014',
        imgText: 'In Return Album Cover',
        youtubeLink: 'https://www.youtube.com/watch?v=QMssNXBCCl0&ab_channel=ODESZA',
    },
    {
        albumCover: '../Assets/Images/Logic_Welcome_To_Forever.jpg',
        trackTitle: '925',
        trackAuthor: 'Logic',
        trackAudio: '../Assets/Audio/Logic-925-10s.mp3',
        category: 'Hip Hop',
        description: '925 by Logic and Producted by Swiff D. Launched in 2013',
        imgText: '925 Music Cover',
        youtubeLink: 'https://www.youtube.com/watch?v=V2mhwTri34A&ab_channel=SwagyTracks',
    },
    {
        albumCover: '../Assets/Images/Learn_to_Exist_by_The_Jungle_Giants.jpg',
        trackTitle: "She's a Riot",
        trackAuthor: 'The Jungle Giants',
        trackAudio: '../Assets/Audio/TheJungleGiants-ShesARiot-10s.mp3',
        category: 'Indie',
        description: '925 by Logic and Producted by Swiff D. Launched in 2013',
        imgText: 'Learn To Exist Album Cover',
        youtubeLink: 'https://www.youtube.com/watch?v=ZbnN5bA-iUM&ab_channel=TheJungleGiants',
    },
]

export default tracks;